package viwer;

import control.DaoManager;
import control.GUIManager;
import domain.Erva;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import swing.LDASwingUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this
 * template
 */
/**
 *
 * @author LUIS DAS ARTIMANHAS
 */
public class DialogCadastroProduto extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro
     */
    private Erva ervaSelecionada = null;
    private String title = "CADASTRO DE PRODUTOS";
    public DialogCadastroProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FORM = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PaineldeCad1 = new javax.swing.JPanel();
        btnNovo1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        painelEnderec = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPesqProd = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSabor = new javax.swing.JLabel();
        txtSabor = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        lblComplem = new javax.swing.JLabel();
        spnPeso = new javax.swing.JSpinner();
        lblComplem2 = new javax.swing.JLabel();
        spnEstoque = new javax.swing.JSpinner();
        lblObs = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setAlignmentX(50.0F);
        background.setAlignmentY(50.0F);
        background.setMinimumSize(new java.awt.Dimension(720, 720));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50);
        flowLayout1.setAlignOnBaseline(true);
        background.setLayout(flowLayout1);

        jScrollPane1.setAlignmentX(50.0F);
        jScrollPane1.setAlignmentY(50.0F);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(720, 600));

        FORM.setBackground(new java.awt.Color(255, 255, 255));
        FORM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FORM.setForeground(new java.awt.Color(255, 255, 255));
        FORM.setAlignmentX(100.0F);
        FORM.setAlignmentY(100.0F);
        FORM.setAutoscrolls(true);
        FORM.setMaximumSize(new java.awt.Dimension(720, 32767));
        FORM.setMinimumSize(new java.awt.Dimension(720, 600));
        FORM.setPreferredSize(new java.awt.Dimension(720, 600));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15);
        flowLayout2.setAlignOnBaseline(true);
        FORM.setLayout(flowLayout2);

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trots/Trots_com_Slogan_Logo_ico.png"))); // NOI18N
        Logo.setAlignmentX(50.0F);
        Logo.setAlignmentY(50.0F);
        FORM.add(Logo);

        PaineldeCad1.setBackground(new java.awt.Color(204, 204, 204));
        PaineldeCad1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        PaineldeCad1.setForeground(new java.awt.Color(0, 0, 0));
        PaineldeCad1.setAlignmentX(50.0F);
        PaineldeCad1.setAlignmentY(50.0F);
        PaineldeCad1.setMaximumSize(new java.awt.Dimension(300, 500));
        PaineldeCad1.setMinimumSize(new java.awt.Dimension(300, 300));

        btnNovo1.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo1.setForeground(new java.awt.Color(0, 0, 0));
        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo1.setMnemonic('N');
        btnNovo1.setText("Novo");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        btnCancelar1.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Save.png"))); // NOI18N
        btnAlterar.setMnemonic('A');
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        painelEnderec.setBackground(new java.awt.Color(51, 51, 51));
        painelEnderec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black));
        painelEnderec.setAlignmentX(50.0F);
        painelEnderec.setAlignmentY(50.0F);
        painelEnderec.setAutoscrolls(true);
        painelEnderec.setLayout(new java.awt.GridLayout(7, 2, 15, 15));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar Produto Existente");
        painelEnderec.add(jLabel1);

        btnPesqProd.setBackground(new java.awt.Color(255, 255, 255));
        btnPesqProd.setForeground(new java.awt.Color(0, 0, 0));
        btnPesqProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/zoom_16x16.gif"))); // NOI18N
        btnPesqProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqProdActionPerformed(evt);
            }
        });
        painelEnderec.add(btnPesqProd);

        lblNome.setBackground(new java.awt.Color(255, 255, 255));
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Smile.png"))); // NOI18N
        lblNome.setText("Nome");
        lblNome.setAlignmentX(10.0F);
        lblNome.setAlignmentY(10.0F);
        painelEnderec.add(lblNome);

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setText("SKU10");
        txtNome.setAlignmentX(10.0F);
        txtNome.setAlignmentY(10.0F);
        txtNome.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        painelEnderec.add(txtNome);

        lblSabor.setForeground(new java.awt.Color(255, 255, 255));
        lblSabor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Retort.png"))); // NOI18N
        lblSabor.setText("Sabor");
        lblSabor.setAlignmentX(10.0F);
        lblSabor.setAlignmentY(10.0F);
        painelEnderec.add(lblSabor);

        txtSabor.setBackground(new java.awt.Color(255, 255, 255));
        txtSabor.setForeground(new java.awt.Color(0, 0, 0));
        txtSabor.setText("Eucalipto");
        txtSabor.setAlignmentX(10.0F);
        txtSabor.setAlignmentY(10.0F);
        txtSabor.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        painelEnderec.add(txtSabor);

        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        lblNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Dollar.png"))); // NOI18N
        lblNum.setText("  Valor (R$)");
        lblNum.setAlignmentX(10.0F);
        lblNum.setAlignmentY(10.0F);
        painelEnderec.add(lblNum);

        spnValor.setModel(new javax.swing.SpinnerNumberModel(10.85f, 1.0f, null, 1.0f));
        spnValor.setAlignmentX(10.0F);
        spnValor.setAlignmentY(10.0F);
        spnValor.setAutoscrolls(true);
        painelEnderec.add(spnValor);

        lblComplem.setForeground(new java.awt.Color(255, 255, 255));
        lblComplem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Target.png"))); // NOI18N
        lblComplem.setText("Peso (G)");
        lblComplem.setAlignmentX(10.0F);
        lblComplem.setAlignmentY(10.0F);
        painelEnderec.add(lblComplem);

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnPeso.setAlignmentX(10.0F);
        spnPeso.setAlignmentY(10.0F);
        spnPeso.setAutoscrolls(true);
        painelEnderec.add(spnPeso);

        lblComplem2.setForeground(new java.awt.Color(255, 255, 255));
        lblComplem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Table.png"))); // NOI18N
        lblComplem2.setText("Quantidade Em Estoque");
        lblComplem2.setAlignmentX(10.0F);
        lblComplem2.setAlignmentY(10.0F);
        painelEnderec.add(lblComplem2);

        spnEstoque.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 10));
        spnEstoque.setAlignmentX(10.0F);
        spnEstoque.setAlignmentY(10.0F);
        spnEstoque.setAutoscrolls(true);
        painelEnderec.add(spnEstoque);

        lblObs.setBackground(new java.awt.Color(255, 255, 255));
        lblObs.setForeground(new java.awt.Color(255, 255, 255));
        lblObs.setText("Descrição");
        painelEnderec.add(lblObs);

        txtObs.setEditable(false);
        txtObs.setBackground(new java.awt.Color(255, 255, 255));
        txtObs.setForeground(new java.awt.Color(0, 0, 0));
        txtObs.setText("Selecione um");
        txtObs.setAlignmentX(10.0F);
        txtObs.setAlignmentY(10.0F);
        txtObs.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtObs.setEnabled(false);
        txtObs.setMinimumSize(new java.awt.Dimension(100, 26));
        painelEnderec.add(txtObs);

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/shopping_cart_(delete)_16x16.gif"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaineldeCad1Layout = new javax.swing.GroupLayout(PaineldeCad1);
        PaineldeCad1.setLayout(PaineldeCad1Layout);
        PaineldeCad1Layout.setHorizontalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaineldeCad1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelEnderec, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        PaineldeCad1Layout.setVerticalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaineldeCad1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelEnderec, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        FORM.add(PaineldeCad1);

        jScrollPane1.setViewportView(FORM);

        background.add(jScrollPane1);

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        ervaSelecionada = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnPesqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqProdActionPerformed
        // TODO add your handling code here:
        GUIManager gui = GUIManager.getMyInstance();
        
        ervaSelecionada = gui.abrirBuscaProd();
        if (ervaSelecionada != null) {
            txtNome.setText(ervaSelecionada.getNome());
        }
    }//GEN-LAST:event_btnPesqProdActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        GUIManager gui = GUIManager.getMyInstance();
        gui.msgWIP(this);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        GUIManager gui = GUIManager.getMyInstance();
        gui.msgWIP(this);
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // TODO add your handling code here
        GUIManager gui = GUIManager.getMyInstance();
        DaoManager dao = gui.getDaoManager();
        String nome = txtNome.getText();
        String sabor = txtSabor.getText();
        float valor = (float) spnValor.getValue();
        int peso = (int) spnPeso.getValue();
        int qtdeEstoque = (int) spnEstoque.getValue();
        String descricao = txtObs.getText();

            LDASwingUtils.message(this, "Operação em andamento...", title);
            try {
                // INSERIR
                ervaSelecionada = dao.InserirErva(nome, sabor, peso, valor, qtdeEstoque, descricao);
                LDASwingUtils.message(this, "Produto: " + nome + ". Cadastrado com sucesso!", title);
                this.dispose();
            } catch (HibernateException ex) {
                LDASwingUtils.messageError(this, "ERRO ao inserir Produto! " + ex, title);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DialogCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnNovo1ActionPerformed

    private boolean validarCampos() {
        String msgError = "";

        msgError = LDASwingUtils.validarCampo(txtNome, lblNome);
        msgError = LDASwingUtils.validarCampo(txtSabor, lblSabor);
        msgError = LDASwingUtils.validarCampo(txtObs, lblObs);

        if (msgError.isEmpty()) {
//            não a erros
            return true;
        } else {
            //            mostra o erro
            JOptionPane.showMessageDialog(
                    this,
                    msgError,
                    title,
                    JOptionPane.ERROR_MESSAGE
            );
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FORM;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PaineldeCad1;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnPesqProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplem;
    private javax.swing.JLabel lblComplem2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblSabor;
    private javax.swing.JPanel painelEnderec;
    private javax.swing.JSpinner spnEstoque;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtSabor;
    // End of variables declaration//GEN-END:variables
}
