package viwer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author 2023122760328
 */
public class DialogCadastroProduto extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro
     */
    public DialogCadastroProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FORM = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PaineldeCad1 = new javax.swing.JPanel();
        btnNovo1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        painelEnderec = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPesqProd = new javax.swing.JButton();
        lblCEP = new javax.swing.JLabel();
        txtEnder1 = new javax.swing.JTextField();
        lblEnder = new javax.swing.JLabel();
        txtEnder = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblComplem = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        lblComplem2 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setAlignmentX(50.0F);
        background.setAlignmentY(50.0F);
        background.setMinimumSize(new java.awt.Dimension(720, 720));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50);
        flowLayout1.setAlignOnBaseline(true);
        background.setLayout(flowLayout1);

        jScrollPane1.setAlignmentX(50.0F);
        jScrollPane1.setAlignmentY(50.0F);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(720, 600));

        FORM.setBackground(new java.awt.Color(255, 255, 255));
        FORM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FORM.setForeground(new java.awt.Color(255, 255, 255));
        FORM.setAlignmentX(100.0F);
        FORM.setAlignmentY(100.0F);
        FORM.setAutoscrolls(true);
        FORM.setMaximumSize(new java.awt.Dimension(720, 32767));
        FORM.setMinimumSize(new java.awt.Dimension(720, 600));
        FORM.setPreferredSize(new java.awt.Dimension(720, 600));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15);
        flowLayout2.setAlignOnBaseline(true);
        FORM.setLayout(flowLayout2);

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trots/Trots_com_Slogan_Logo_ico.png"))); // NOI18N
        Logo.setAlignmentX(50.0F);
        Logo.setAlignmentY(50.0F);
        FORM.add(Logo);

        PaineldeCad1.setBackground(new java.awt.Color(204, 204, 204));
        PaineldeCad1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        PaineldeCad1.setForeground(new java.awt.Color(0, 0, 0));
        PaineldeCad1.setAlignmentX(50.0F);
        PaineldeCad1.setAlignmentY(50.0F);
        PaineldeCad1.setMaximumSize(new java.awt.Dimension(300, 500));
        PaineldeCad1.setMinimumSize(new java.awt.Dimension(300, 300));

        btnNovo1.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo1.setForeground(new java.awt.Color(0, 0, 0));
        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo1.setMnemonic('N');
        btnNovo1.setText("Novo");

        btnCancelar1.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Save.png"))); // NOI18N
        btnAlterar.setMnemonic('A');
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        painelEnderec.setBackground(new java.awt.Color(51, 51, 51));
        painelEnderec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black));
        painelEnderec.setAlignmentX(50.0F);
        painelEnderec.setAlignmentY(50.0F);
        painelEnderec.setAutoscrolls(true);
        painelEnderec.setLayout(new java.awt.GridLayout(6, 2, 15, 15));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar Produto Existente");
        painelEnderec.add(jLabel1);

        btnPesqProd.setBackground(new java.awt.Color(255, 255, 255));
        btnPesqProd.setForeground(new java.awt.Color(0, 0, 0));
        btnPesqProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/zoom_16x16.gif"))); // NOI18N
        btnPesqProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqProdActionPerformed(evt);
            }
        });
        painelEnderec.add(btnPesqProd);

        lblCEP.setBackground(new java.awt.Color(255, 255, 255));
        lblCEP.setForeground(new java.awt.Color(255, 255, 255));
        lblCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Smile.png"))); // NOI18N
        lblCEP.setText("Nome");
        lblCEP.setAlignmentX(10.0F);
        lblCEP.setAlignmentY(10.0F);
        painelEnderec.add(lblCEP);

        txtEnder1.setBackground(new java.awt.Color(255, 255, 255));
        txtEnder1.setForeground(new java.awt.Color(0, 0, 0));
        txtEnder1.setText("SKU10");
        txtEnder1.setAlignmentX(10.0F);
        txtEnder1.setAlignmentY(10.0F);
        txtEnder1.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        painelEnderec.add(txtEnder1);

        lblEnder.setForeground(new java.awt.Color(255, 255, 255));
        lblEnder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Retort.png"))); // NOI18N
        lblEnder.setText("Sabor");
        lblEnder.setAlignmentX(10.0F);
        lblEnder.setAlignmentY(10.0F);
        painelEnderec.add(lblEnder);

        txtEnder.setBackground(new java.awt.Color(255, 255, 255));
        txtEnder.setForeground(new java.awt.Color(0, 0, 0));
        txtEnder.setText("Eucalipto");
        txtEnder.setAlignmentX(10.0F);
        txtEnder.setAlignmentY(10.0F);
        txtEnder.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        painelEnderec.add(txtEnder);

        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        lblNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Dollar.png"))); // NOI18N
        lblNum.setText("  Valor (R$)");
        lblNum.setAlignmentX(10.0F);
        lblNum.setAlignmentY(10.0F);
        painelEnderec.add(lblNum);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(10.85d, 1.0d, null, 1.0d));
        jSpinner1.setAlignmentX(10.0F);
        jSpinner1.setAlignmentY(10.0F);
        jSpinner1.setAutoscrolls(true);
        painelEnderec.add(jSpinner1);

        lblComplem.setForeground(new java.awt.Color(255, 255, 255));
        lblComplem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Target.png"))); // NOI18N
        lblComplem.setText("Peso (G)");
        lblComplem.setAlignmentX(10.0F);
        lblComplem.setAlignmentY(10.0F);
        painelEnderec.add(lblComplem);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner2.setAlignmentX(10.0F);
        jSpinner2.setAlignmentY(10.0F);
        jSpinner2.setAutoscrolls(true);
        painelEnderec.add(jSpinner2);

        lblComplem2.setForeground(new java.awt.Color(255, 255, 255));
        lblComplem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Table.png"))); // NOI18N
        lblComplem2.setText("Quantidade Em Estoque");
        lblComplem2.setAlignmentX(10.0F);
        lblComplem2.setAlignmentY(10.0F);
        painelEnderec.add(lblComplem2);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 10));
        jSpinner3.setAlignmentX(10.0F);
        jSpinner3.setAlignmentY(10.0F);
        jSpinner3.setAutoscrolls(true);
        painelEnderec.add(jSpinner3);

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/shopping_cart_(delete)_16x16.gif"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaineldeCad1Layout = new javax.swing.GroupLayout(PaineldeCad1);
        PaineldeCad1.setLayout(PaineldeCad1Layout);
        PaineldeCad1Layout.setHorizontalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaineldeCad1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelEnderec, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PaineldeCad1Layout.setVerticalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaineldeCad1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelEnderec, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGap(68, 68, 68)))
        );

        FORM.add(PaineldeCad1);

        jScrollPane1.setViewportView(FORM);

        background.add(jScrollPane1);

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnPesqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqProdActionPerformed
        // TODO add your handling code here:
//        DialogBuscaProd tela = new DialogBuscaProd(this,true);
//        
//        tela.setVisible(true);
    }//GEN-LAST:event_btnPesqProdActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCadastro dialog = new DialogCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FORM;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PaineldeCad1;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnPesqProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblComplem;
    private javax.swing.JLabel lblComplem2;
    private javax.swing.JLabel lblEnder;
    private javax.swing.JLabel lblNum;
    private javax.swing.JPanel painelEnderec;
    private javax.swing.JTextField txtEnder;
    private javax.swing.JTextField txtEnder1;
    // End of variables declaration//GEN-END:variables
}
