package viwer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this
 * template
 */
/**
 *
 * @author LUIS DAS ARTIMANHAS
 */
public class DialogBuscaProd extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro
     */
    public DialogBuscaProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FORM = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PaineldeCad1 = new javax.swing.JPanel();
        painelEnderec = new javax.swing.JPanel();
        lblProd = new javax.swing.JLabel();
        cmbProd = new javax.swing.JComboBox<>();
        lblSku = new javax.swing.JLabel();
        txtSku = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblEstoque = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        lblObs = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setAlignmentX(50.0F);
        background.setAlignmentY(50.0F);
        background.setMinimumSize(new java.awt.Dimension(720, 720));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50);
        flowLayout1.setAlignOnBaseline(true);
        background.setLayout(flowLayout1);

        jScrollPane1.setAlignmentX(50.0F);
        jScrollPane1.setAlignmentY(50.0F);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(720, 600));

        FORM.setBackground(new java.awt.Color(255, 255, 255));
        FORM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FORM.setForeground(new java.awt.Color(255, 255, 255));
        FORM.setAlignmentX(100.0F);
        FORM.setAlignmentY(100.0F);
        FORM.setAutoscrolls(true);
        FORM.setMaximumSize(new java.awt.Dimension(720, 32767));
        FORM.setMinimumSize(new java.awt.Dimension(720, 600));
        FORM.setPreferredSize(new java.awt.Dimension(720, 600));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15);
        flowLayout2.setAlignOnBaseline(true);
        FORM.setLayout(flowLayout2);

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trots/Trots_com_Slogan_Logo_ico.png"))); // NOI18N
        Logo.setAlignmentX(50.0F);
        Logo.setAlignmentY(50.0F);
        FORM.add(Logo);

        PaineldeCad1.setBackground(new java.awt.Color(204, 204, 204));
        PaineldeCad1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        PaineldeCad1.setForeground(new java.awt.Color(0, 0, 0));
        PaineldeCad1.setAlignmentX(50.0F);
        PaineldeCad1.setAlignmentY(50.0F);
        PaineldeCad1.setMaximumSize(new java.awt.Dimension(300, 500));
        PaineldeCad1.setMinimumSize(new java.awt.Dimension(300, 300));

        painelEnderec.setBackground(new java.awt.Color(51, 51, 51));
        painelEnderec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black));
        painelEnderec.setAlignmentX(50.0F);
        painelEnderec.setAlignmentY(50.0F);
        painelEnderec.setAutoscrolls(true);
        painelEnderec.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        lblProd.setBackground(new java.awt.Color(255, 255, 255));
        lblProd.setForeground(new java.awt.Color(255, 255, 255));
        lblProd.setText("Produto");
        painelEnderec.add(lblProd);

        cmbProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Um", "Aqui vai ter o select do banco de dados" }));
        painelEnderec.add(cmbProd);

        lblSku.setBackground(new java.awt.Color(255, 255, 255));
        lblSku.setForeground(new java.awt.Color(255, 255, 255));
        lblSku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Smile.png"))); // NOI18N
        lblSku.setText("SKU");
        lblSku.setAlignmentX(10.0F);
        lblSku.setAlignmentY(10.0F);
        painelEnderec.add(lblSku);

        txtSku.setEditable(false);
        txtSku.setBackground(new java.awt.Color(255, 255, 255));
        txtSku.setForeground(new java.awt.Color(0, 0, 0));
        txtSku.setText("SKU10");
        txtSku.setAlignmentX(10.0F);
        txtSku.setAlignmentY(10.0F);
        txtSku.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSku.setEnabled(false);
        painelEnderec.add(txtSku);

        lblPeso.setBackground(new java.awt.Color(255, 255, 255));
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setText("Peso (G)");
        painelEnderec.add(lblPeso);

        txtPeso.setEditable(false);
        txtPeso.setBackground(new java.awt.Color(255, 255, 255));
        txtPeso.setForeground(new java.awt.Color(0, 0, 0));
        txtPeso.setText("500");
        txtPeso.setAlignmentX(10.0F);
        txtPeso.setAlignmentY(10.0F);
        txtPeso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPeso.setEnabled(false);
        painelEnderec.add(txtPeso);

        lblEstoque.setBackground(new java.awt.Color(255, 255, 255));
        lblEstoque.setForeground(new java.awt.Color(255, 255, 255));
        lblEstoque.setText("Em Estoque");
        painelEnderec.add(lblEstoque);

        txtEstoque.setEditable(false);
        txtEstoque.setBackground(new java.awt.Color(255, 255, 255));
        txtEstoque.setForeground(new java.awt.Color(0, 0, 0));
        txtEstoque.setText("1");
        txtEstoque.setAlignmentX(10.0F);
        txtEstoque.setAlignmentY(10.0F);
        txtEstoque.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEstoque.setEnabled(false);
        painelEnderec.add(txtEstoque);

        lblObs.setBackground(new java.awt.Color(255, 255, 255));
        lblObs.setForeground(new java.awt.Color(255, 255, 255));
        lblObs.setText("Descrição");
        painelEnderec.add(lblObs);

        txtObs.setEditable(false);
        txtObs.setBackground(new java.awt.Color(255, 255, 255));
        txtObs.setForeground(new java.awt.Color(0, 0, 0));
        txtObs.setText("O sabor do campo em forma de erva. A Limão Caipira traz a intensidade e a refrescância  do limão associado ao sabor único que só a erva mate tem. ");
        txtObs.setAlignmentX(10.0F);
        txtObs.setAlignmentY(10.0F);
        txtObs.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtObs.setEnabled(false);
        txtObs.setMinimumSize(new java.awt.Dimension(100, 26));
        painelEnderec.add(txtObs);

        javax.swing.GroupLayout PaineldeCad1Layout = new javax.swing.GroupLayout(PaineldeCad1);
        PaineldeCad1.setLayout(PaineldeCad1Layout);
        PaineldeCad1Layout.setHorizontalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEnderec, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PaineldeCad1Layout.setVerticalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEnderec, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        FORM.add(PaineldeCad1);

        jScrollPane1.setViewportView(FORM);

        background.add(jScrollPane1);

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBuscaProd dialog = new DialogBuscaProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FORM;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PaineldeCad1;
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblProd;
    private javax.swing.JLabel lblSku;
    private javax.swing.JPanel painelEnderec;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSku;
    // End of variables declaration//GEN-END:variables
}
