package viwer;

import control.CustomTableModel;
import control.DaoManager;
import control.GUIManager;
import control.LDAMainUtils;
import domain.Cliente;
import domain.Erva;
import domain.ItemPedido;
import domain.Venda;
import java.util.List;
import javax.swing.JOptionPane;
import swing.LDASwingUtils;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this
 * template
 */
/**
 *
 * @author LUIS DAS ARTIMANHAS
 */
public class DialogCadastroVenda extends javax.swing.JDialog {

    private List<String> getters = List.of("getQdte", "getTipo", "getValorDaUnidade", "getSubTotal");
//    private CustomTableModel tableModelItemPedido;
    private CustomTableModel<ItemPedido> tableModelItemPedido;
    private Cliente cliSelecionado = null;
    private String title = "REGISTRAR VENDA";

    /**
     * Creates new form Cadastro
     */
    public DialogCadastroVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Amarro o JTable com o meu Abstract Table Model
//        tableModelItemPedido = new CustomTableModel(new ArrayList<ItemPedido>(), getters, ItemPedido.class);
//        tblPedido.setModel(tableModelItemPedido);

        // Amarro o JTable com o meu AUTO Abstract Table Model
        tableModelItemPedido = new CustomTableModel(getters, ItemPedido.class);
        tblPedido.setModel(tableModelItemPedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup = new javax.swing.JPopupMenu();
        inserir = new javax.swing.JMenuItem();
        excluir = new javax.swing.JMenuItem();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FORM = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PaineldeCad1 = new javax.swing.JPanel();
        btnNovo1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        overflow = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        lblValor = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblLanche = new javax.swing.JLabel();
        cmbSabor = new javax.swing.JComboBox();
        txtNome = new javax.swing.JTextField();
        btnPesqCli = new javax.swing.JButton();
        btnAddLanche = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spnQtde = new javax.swing.JSpinner();
        btnAddLanche1 = new javax.swing.JButton();
        lblWait = new javax.swing.JButton();
        lblQtdeCard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        inserir.setText("inserir");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });
        Popup.add(inserir);

        excluir.setText("excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        Popup.add(excluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(720, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(530, 530));
        background.setPreferredSize(new java.awt.Dimension(430, 530));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15);
        flowLayout1.setAlignOnBaseline(true);
        background.setLayout(flowLayout1);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 400));

        FORM.setBackground(new java.awt.Color(255, 255, 255));
        FORM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FORM.setForeground(new java.awt.Color(255, 255, 255));
        FORM.setAlignmentX(100.0F);
        FORM.setAlignmentY(100.0F);
        FORM.setAutoscrolls(true);
        FORM.setMaximumSize(new java.awt.Dimension(1024, 800));
        FORM.setMinimumSize(new java.awt.Dimension(650, 650));
        FORM.setName(""); // NOI18N
        FORM.setPreferredSize(new java.awt.Dimension(650, 650));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15);
        flowLayout2.setAlignOnBaseline(true);
        FORM.setLayout(flowLayout2);

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trots/Trots_com_Slogan_Logo_ico.png"))); // NOI18N
        Logo.setAlignmentX(50.0F);
        Logo.setAlignmentY(50.0F);
        FORM.add(Logo);

        PaineldeCad1.setBackground(new java.awt.Color(204, 204, 204));
        PaineldeCad1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registrar Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        PaineldeCad1.setForeground(new java.awt.Color(0, 0, 0));
        PaineldeCad1.setAlignmentX(50.0F);
        PaineldeCad1.setAlignmentY(50.0F);
        PaineldeCad1.setAutoscrolls(true);
        PaineldeCad1.setMaximumSize(new java.awt.Dimension(500, 500));
        PaineldeCad1.setMinimumSize(new java.awt.Dimension(450, 450));
        PaineldeCad1.setName(""); // NOI18N
        PaineldeCad1.setPreferredSize(new java.awt.Dimension(450, 450));

        btnNovo1.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo1.setForeground(new java.awt.Color(0, 0, 0));
        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        btnNovo1.setText("Confirmar Venda");
        btnNovo1.setAutoscrolls(true);
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        btnCancelar1.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        overflow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Ervas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tblPedido.setBackground(new java.awt.Color(255, 255, 255));
        tblPedido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblPedido.setForeground(new java.awt.Color(0, 0, 0));
        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"sad",  new Integer(7), null, null},
                {"Erva Mate - Menta & Cereja ",  new Integer(3), null, null},
                {"aasd",  new Integer(5), null, null},
                {"aasdasd",  new Integer(8), null, null}
            },
            new String [] {
                "Tipo", "Qtde", "ValorDaUnidade", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedido.setComponentPopupMenu(Popup);
        tblPedido.setGridColor(new java.awt.Color(0, 0, 0));
        tblPedido.setMinimumSize(new java.awt.Dimension(400, 520));
        tblPedido.setPreferredSize(new java.awt.Dimension(400, 520));
        tblPedido.setSelectionBackground(new java.awt.Color(0, 0, 204));
        tblPedido.setShowGrid(true);
        tblPedido.getTableHeader().setResizingAllowed(false);
        tblPedido.getTableHeader().setReorderingAllowed(false);
        overflow.setViewportView(tblPedido);

        lblValor.setBackground(new java.awt.Color(255, 255, 255));
        lblValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblValor.setForeground(new java.awt.Color(0, 0, 0));
        lblValor.setText("TOTAL: R$ 0,0");

        lblNome1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(0, 0, 0));
        lblNome1.setText("Cliente");

        lblLanche.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLanche.setForeground(new java.awt.Color(0, 0, 0));
        lblLanche.setText("Erva");

        cmbSabor.setBackground(new java.awt.Color(255, 255, 255));
        cmbSabor.setForeground(new java.awt.Color(0, 0, 0));
        cmbSabor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Um", " " }));
        cmbSabor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSaborItemStateChanged(evt);
            }
        });

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setText("Teste");
        txtNome.setEnabled(false);

        btnPesqCli.setBackground(new java.awt.Color(255, 255, 255));
        btnPesqCli.setForeground(new java.awt.Color(0, 0, 0));
        btnPesqCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/zoom_16x16.gif"))); // NOI18N
        btnPesqCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesqCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCliActionPerformed(evt);
            }
        });

        btnAddLanche.setBackground(new java.awt.Color(255, 255, 255));
        btnAddLanche.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLanche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/delete_16x16.gif"))); // NOI18N
        btnAddLanche.setText("Excluir");
        btnAddLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Qtde");

        spnQtde.setModel(new javax.swing.SpinnerNumberModel(5, 0, 10, 1));
        spnQtde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQtdeStateChanged(evt);
            }
        });

        btnAddLanche1.setBackground(new java.awt.Color(255, 255, 255));
        btnAddLanche1.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLanche1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnAddLanche1.setText("Incluir");
        btnAddLanche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });

        lblWait.setBackground(new java.awt.Color(255, 255, 255));
        lblWait.setForeground(new java.awt.Color(0, 0, 0));
        lblWait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/wait_16x16.gif"))); // NOI18N
        lblWait.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblWait.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        lblQtdeCard.setBackground(new java.awt.Color(255, 255, 255));
        lblQtdeCard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQtdeCard.setForeground(new java.awt.Color(0, 0, 0));
        lblQtdeCard.setText("0");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/shopping_cart_16x16.gif"))); // NOI18N

        javax.swing.GroupLayout PaineldeCad1Layout = new javax.swing.GroupLayout(PaineldeCad1);
        PaineldeCad1.setLayout(PaineldeCad1Layout);
        PaineldeCad1Layout.setHorizontalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaineldeCad1Layout.createSequentialGroup()
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaineldeCad1Layout.createSequentialGroup()
                        .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaineldeCad1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PaineldeCad1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PaineldeCad1Layout.createSequentialGroup()
                                        .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaineldeCad1Layout.createSequentialGroup()
                                                .addComponent(lblNome1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                                                .addComponent(lblLanche)
                                                .addGap(7, 7, 7)))
                                        .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                                                .addGap(209, 209, 209)
                                                .addComponent(btnAddLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaineldeCad1Layout.createSequentialGroup()
                                                    .addComponent(cmbSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblWait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaineldeCad1Layout.createSequentialGroup()
                                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnPesqCli, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaineldeCad1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnAddLanche1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaineldeCad1Layout.createSequentialGroup()
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtdeCard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(overflow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        PaineldeCad1Layout.setVerticalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaineldeCad1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesqCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNome1)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLanche)
                            .addComponent(cmbSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaineldeCad1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblWait, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddLanche1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overflow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtdeCard)
                    .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lblValor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        FORM.add(PaineldeCad1);

        jScrollPane1.setViewportView(FORM);

        background.add(jScrollPane1);

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed
        // TODO add your handling code here:
        GUIManager gui = GUIManager.getMyInstance();
        Erva erva = (Erva) cmbSabor.getSelectedItem();
        int qtde = (int) spnQtde.getValue();
        String tipo = erva.getSabor();

        inserirTabela(erva, tipo, qtde);
    }//GEN-LAST:event_inserirActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // TODO add your handling code here:
        GUIManager gui = GUIManager.getMyInstance();
        DaoManager dao = gui.getDaoManager();
        List ListaItensPedido = tableModelItemPedido.getLista();

        if (cliSelecionado != null) {
            Venda venda = dao.inserirVenda(cliSelecionado, ListaItensPedido);
            LDASwingUtils.message(this, "Pedido " + venda.getIdVenda() + " inserido com sucesso.", title);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente.", title, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void btnPesqCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCliActionPerformed
        // TODO add your handling code here:
        GUIManager gui = GUIManager.getMyInstance();

        cliSelecionado = gui.abrirBuscaCli();
        if (cliSelecionado != null) {
            txtNome.setText(cliSelecionado.getNome());
        }
    }//GEN-LAST:event_btnPesqCliActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        int linha = tblPedido.getSelectedRow();

        if (linha >= 0) {
            excluirVenda(linha);
        } else {
            LDASwingUtils.messageError(this, "Selecione ao menos uma linha", title);
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:    
        lblWait.setVisible(true);
        GUIManager gui = GUIManager.getMyInstance();
        gui.carregarCombo(cmbSabor, Erva.class);
        lblWait.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void cmbSaborItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSaborItemStateChanged
        // TODO add your handling code here:
        atualizarValorTotal();
    }//GEN-LAST:event_cmbSaborItemStateChanged

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        cliSelecionado = null;
        this.setVisible(false);
        limparCampos();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void spnQtdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQtdeStateChanged
        // TODO add your handling code here:
        atualizarValorTotal();
    }//GEN-LAST:event_spnQtdeStateChanged

//    FUNÇÕES UTEIS;
    private void inserirTabela(Erva erva, String tipo, int qtde) {
        //    Erva erva, Venda venda, String tipo, int Qdte
        ItemPedido item = new ItemPedido(erva, null, tipo, qtde);
        tableModelItemPedido.adicionar(item);
        atualizarValorTotal();
    }

    private void excluirVenda(int linha) {
        int confirmPane = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente Excluir o item do carrinho?"
        );

        if (confirmPane == JOptionPane.YES_OPTION) {
//            deleta multiplas linhas selecionadas
            while (linha >= 0) {
                tableModelItemPedido.remover(linha);
                linha = tblPedido.getSelectedRow();
            }
            LDASwingUtils.message(this, "Excluido com sucesso!", title);
            atualizarValorTotal();
        }
    }

    private void atualizarValorTotal() {
        float valorTotal = 0;
        int tam = tableModelItemPedido.getRowCount();
        
        for (int i = 0; i < tam; i++) {
            ItemPedido item = (ItemPedido) tableModelItemPedido.getItem(i);

            valorTotal = LDAMainUtils.CalcValorTotal(item.getSubTotal(), valorTotal);
        }

        lblQtdeCard.setText(String.valueOf(tam));
        lblValor.setText("TOTAL R$:" + valorTotal);
        GUIManager.getMyInstance().log("VALOR TOTAL ATUALIZADO!");
    }

    private void limparCampos() {
        GUIManager gui = GUIManager.getMyInstance();
        int linha = tableModelItemPedido.getRowCount() -1;
        LDASwingUtils.clearTxt(txtNome);
        
//        deleta multiplas linhas selecionadas
        while (linha >= 0) {
            tableModelItemPedido.remover(linha);
            gui.log("VENDA " + linha + " REMOVIDA");
            linha = tableModelItemPedido.getRowCount()-1;
        }
        atualizarValorTotal();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FORM;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PaineldeCad1;
    private javax.swing.JPopupMenu Popup;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAddLanche;
    private javax.swing.JButton btnAddLanche1;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnPesqCli;
    private javax.swing.JComboBox cmbSabor;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JMenuItem inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLanche;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblQtdeCard;
    private javax.swing.JLabel lblValor;
    private javax.swing.JButton lblWait;
    private javax.swing.JScrollPane overflow;
    private javax.swing.JSpinner spnQtde;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
