/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author 2023122760328
 */
public class DialogBuscaProd extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro
     */
    public DialogBuscaProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FORM = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PaineldeCad1 = new javax.swing.JPanel();
        painelEnderec = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblCEP = new javax.swing.JLabel();
        txtEnder1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEnder3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnder4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEnder2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setAlignmentX(50.0F);
        background.setAlignmentY(50.0F);
        background.setMinimumSize(new java.awt.Dimension(720, 720));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50);
        flowLayout1.setAlignOnBaseline(true);
        background.setLayout(flowLayout1);

        jScrollPane1.setAlignmentX(50.0F);
        jScrollPane1.setAlignmentY(50.0F);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(720, 600));

        FORM.setBackground(new java.awt.Color(255, 255, 255));
        FORM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FORM.setForeground(new java.awt.Color(255, 255, 255));
        FORM.setAlignmentX(100.0F);
        FORM.setAlignmentY(100.0F);
        FORM.setAutoscrolls(true);
        FORM.setMaximumSize(new java.awt.Dimension(720, 32767));
        FORM.setMinimumSize(new java.awt.Dimension(720, 600));
        FORM.setPreferredSize(new java.awt.Dimension(720, 600));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15);
        flowLayout2.setAlignOnBaseline(true);
        FORM.setLayout(flowLayout2);

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trots/Trots_com_Slogan_Logo_ico.png"))); // NOI18N
        Logo.setAlignmentX(50.0F);
        Logo.setAlignmentY(50.0F);
        FORM.add(Logo);

        PaineldeCad1.setBackground(new java.awt.Color(204, 204, 204));
        PaineldeCad1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        PaineldeCad1.setForeground(new java.awt.Color(0, 0, 0));
        PaineldeCad1.setAlignmentX(50.0F);
        PaineldeCad1.setAlignmentY(50.0F);
        PaineldeCad1.setMaximumSize(new java.awt.Dimension(300, 500));
        PaineldeCad1.setMinimumSize(new java.awt.Dimension(300, 300));

        painelEnderec.setBackground(new java.awt.Color(51, 51, 51));
        painelEnderec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black));
        painelEnderec.setAlignmentX(50.0F);
        painelEnderec.setAlignmentY(50.0F);
        painelEnderec.setAutoscrolls(true);
        painelEnderec.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        jLabel1.setText("Produto");
        painelEnderec.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Um", "Aqui vai ter o select do banco de dados" }));
        painelEnderec.add(jComboBox1);

        lblCEP.setBackground(new java.awt.Color(255, 255, 255));
        lblCEP.setForeground(new java.awt.Color(255, 255, 255));
        lblCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/Smile.png"))); // NOI18N
        lblCEP.setText("SKU");
        lblCEP.setAlignmentX(10.0F);
        lblCEP.setAlignmentY(10.0F);
        painelEnderec.add(lblCEP);

        txtEnder1.setEditable(false);
        txtEnder1.setBackground(new java.awt.Color(255, 255, 255));
        txtEnder1.setForeground(new java.awt.Color(0, 0, 0));
        txtEnder1.setText("SKU10");
        txtEnder1.setAlignmentX(10.0F);
        txtEnder1.setAlignmentY(10.0F);
        txtEnder1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEnder1.setEnabled(false);
        txtEnder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnder1ActionPerformed(evt);
            }
        });
        painelEnderec.add(txtEnder1);

        jLabel3.setText("Peso (G)");
        painelEnderec.add(jLabel3);

        txtEnder3.setEditable(false);
        txtEnder3.setBackground(new java.awt.Color(255, 255, 255));
        txtEnder3.setForeground(new java.awt.Color(0, 0, 0));
        txtEnder3.setText("500");
        txtEnder3.setAlignmentX(10.0F);
        txtEnder3.setAlignmentY(10.0F);
        txtEnder3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEnder3.setEnabled(false);
        txtEnder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnder3ActionPerformed(evt);
            }
        });
        painelEnderec.add(txtEnder3);

        jLabel4.setText("Em Estoque");
        painelEnderec.add(jLabel4);

        txtEnder4.setEditable(false);
        txtEnder4.setBackground(new java.awt.Color(255, 255, 255));
        txtEnder4.setForeground(new java.awt.Color(0, 0, 0));
        txtEnder4.setText("1");
        txtEnder4.setAlignmentX(10.0F);
        txtEnder4.setAlignmentY(10.0F);
        txtEnder4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEnder4.setEnabled(false);
        txtEnder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnder4ActionPerformed(evt);
            }
        });
        painelEnderec.add(txtEnder4);

        jLabel2.setText("Descrição");
        painelEnderec.add(jLabel2);

        txtEnder2.setEditable(false);
        txtEnder2.setBackground(new java.awt.Color(255, 255, 255));
        txtEnder2.setForeground(new java.awt.Color(0, 0, 0));
        txtEnder2.setText("O sabor do campo em forma de erva. A Limão Caipira traz a intensidade e a refrescância  do limão associado ao sabor único que só a erva mate tem. ");
        txtEnder2.setAlignmentX(10.0F);
        txtEnder2.setAlignmentY(10.0F);
        txtEnder2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEnder2.setEnabled(false);
        txtEnder2.setMinimumSize(new java.awt.Dimension(100, 26));
        txtEnder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnder2ActionPerformed(evt);
            }
        });
        painelEnderec.add(txtEnder2);

        javax.swing.GroupLayout PaineldeCad1Layout = new javax.swing.GroupLayout(PaineldeCad1);
        PaineldeCad1.setLayout(PaineldeCad1Layout);
        PaineldeCad1Layout.setHorizontalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEnderec, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PaineldeCad1Layout.setVerticalGroup(
            PaineldeCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeCad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEnderec, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        FORM.add(PaineldeCad1);

        jScrollPane1.setViewportView(FORM);

        background.add(jScrollPane1);

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnder1ActionPerformed

    private void txtEnder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnder2ActionPerformed

    private void txtEnder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnder3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnder3ActionPerformed

    private void txtEnder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnder4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnder4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCadastro dialog = new DialogCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FORM;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PaineldeCad1;
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JPanel painelEnderec;
    private javax.swing.JTextField txtEnder1;
    private javax.swing.JTextField txtEnder2;
    private javax.swing.JTextField txtEnder3;
    private javax.swing.JTextField txtEnder4;
    // End of variables declaration//GEN-END:variables
}
